Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@Xand6r 
Xand6r
/
utilities-and-scripts
1
0
0
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
utilities-and-scripts/Continous deployment docker compoe file
@Xand6r
Xand6r Create Continous deployment docker compoe file
Latest commit 11ab2b2 on 4 Jan
 History
 1 contributor
61 lines (55 sloc)  1.23 KB
 
version: '3'
    
services:
  #web service
  web:
    container_name: container_name
    image: speakspire/speakspire:latest
    deploy:
        restart_policy:
            condition: any
    ports:
        - 80:80
  
#Volumes
volumes:
  mysql-data:

