version: '3'
    
services:
  #web service
  web:
    container_name: container_name
    image: speakspire/speakspire:latest
    deploy:
        restart_policy:
            condition: any
    ports:
        - 80:80
  
#Volumes
volumes:
  mysql-data:

