export default (data) => {
	console.log(data);
	const {
		full_bio,
		fullname,
		email,
		gender,
		birthdate,
		city,
		phonenumber,
		country,
		experience_years,
		engagement_no,
		highest_education,
		languages,
		unique_selling_proposition,
		links,
		profile_photo,
		cover_photo,
		password,
		education,
		primary_specialty,
		secondary_specialty,
		primary_topic_area,
		secondary_topic_area,
		primary_topic_tags,
		secondary_topic_tags,
		certifications,
		availabilty,
		mode_of_delivery,
		open_for_travel,
		travel_places,
		positions,
		media,
	} = data;
	return Object.freeze({
		name: fullname,
		email,
		sex: gender,
		birthday: birthdate[1],
		phone: phonenumber,
		state: city,
		country,
		years_of_experience: experience_years,
		number_of_engagements: engagement_no,
		highest_level_of_education: highest_education,
		languages,
		usp: unique_selling_proposition,
		bio: full_bio,
		links,
		profile_photo: profile_photo.src,
		cover_photo: cover_photo.src,
		password,
		education,
		expertise: {
			primary_specialty,
			secondary_specialty,
			primary_topic: primary_topic_area,
			secondary_topic: secondary_topic_area,
			primary_tags: primary_topic_tags,
			secondary_tags: secondary_topic_tags,
		},
		certification: certifications,
		preferences: {availabilty, delivery_mode: mode_of_delivery, open_to_travel: open_for_travel, travel: travel_places},
		experience: positions,
		media,
	});
};

const cleanCertification = (data) => {
	data.map(({certification_name, from, institution_name, link, to}) => {
		return {
			institution: institution_name,
			name: certification_name,
			from,
			to,
			proof: link,
		};
	});
};
